---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

title: Homepage
theme: dark # or light
color: zinc

background:
  image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 30 # 0, 30, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 30 # 0, 30, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 30 # 0-100
  
  layout:
  Media:
    style: row
    columns: 4